version: "3.8"

services:
  djangotutorial:
    build: ./djangotutorial
    container_name: djangotutorial
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb

  dash:
    build: ./dash
    container_name: dash
    ports:
      - "8050:8050"
    depends_on:
      - djangotutorial

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
