version: "3.8"

services:
  djangotutorial:
    build: ./djangotutorial
    container_name: djangotutorial
    ports:
      - "8000:8000"  # Пробрасываем порт для Django

  dash:
    build: ./dash
    container_name: dash
    ports:
      - "8050:8050"  # Пробрасываем порт для

  fitness-tracker:
    build: ./fitness-tracker
    ports:
      - "5173:5173"
    volumes:
      - ./fitness-tracker:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
