version: "3.9"

services:
  djangotutorial:
    build: ./djangotutorial
    container_name: djangotutorial
    ports:
      - "8000:8000"  # Пробрасываем порт для Django
    volumes:
      - .:/djangotutorial  # Монтируем весь проект в контейнер
      - static_volume:/djangotutorial/staticfiles  # Монтируем папку для собранных статики

  dash:
    build: ./dash
    container_name: dash
    ports:
      - "8050:8050"  # Пробрасываем порт для

  store:
    build: ./store
    ports:
      - "5173:5173"
    volumes:
      - ./store:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  static_volume:
